using System.Text.Json;
using System.Xml.Schema;

namespace SmartWsdlKit
{
	/// <summary>
	/// Generates OpenAPI 3.x specifications and JSON Schemas from WSDL metadata.
	/// </summary>
	public static class OpenApiGenerator
	{
		/// <summary>
		/// Generates an OpenAPI 3.0 JSON specification string from WSDL metadata.
		/// </summary>
		public static string Generate(WsdlDocument wsdl)
		{
			if (wsdl == null)
				throw new ArgumentNullException(nameof(wsdl));

			var serviceName = wsdl.Services.Count > 0 ? wsdl.Services[0].Name : "SoapService";

			// Root OpenAPI object
			var openApi = new Dictionary<string, object>
			{
				["openapi"] = "3.0.3",
				["info"] = new Dictionary<string, object>
				{
					["title"] = serviceName,
					["version"] = "1.0.0",
					["description"] = $"REST-like API wrapper for SOAP Service {serviceName} generated by SmartWsdlKit."
				},
				["paths"] = GeneratePaths(wsdl),
				["components"] = new Dictionary<string, object>
				{
					["schemas"] = GenerateJsonSchemas(wsdl.Schemas)
				}
			};

			var options = new JsonSerializerOptions
			{
				WriteIndented = true
			};

			return JsonSerializer.Serialize(openApi, options);
		}

		private static Dictionary<string, object> GeneratePaths(WsdlDocument wsdl)
		{
			var paths = new Dictionary<string, object>();

			foreach (var op in wsdl.Operations)
			{
				var routePath = $"/operations/{op.Name}";

				var reqSchemaRef = op.InputElementName != null ? $"#/components/schemas/{SanitizeName(op.InputElementName)}" : null;
				var respSchemaRef = op.OutputElementName != null ? $"#/components/schemas/{SanitizeName(op.OutputElementName)}" : null;

				var postMethod = new Dictionary<string, object>
				{
					["summary"] = $"Invokes SOAP operation {op.Name}",
					["description"] = $"SOAP Action: '{op.SoapAction}'. Style: '{op.Style}'.",
					["responses"] = new Dictionary<string, object>
					{
						["200"] = new Dictionary<string, object>
						{
							["description"] = "SOAP Response payload",
							["content"] = new Dictionary<string, object>
							{
								["text/xml"] = new Dictionary<string, object>
								{
									["schema"] = respSchemaRef != null
										? new Dictionary<string, string> { ["$ref"] = respSchemaRef }
										: new Dictionary<string, string> { ["type"] = "string" }
								}
							}
						}
					}
				};

				if (reqSchemaRef != null)
				{
					postMethod["requestBody"] = new Dictionary<string, object>
					{
						["required"] = true,
						["content"] = new Dictionary<string, object>
						{
							["text/xml"] = new Dictionary<string, object>
							{
								["schema"] = new Dictionary<string, string> { ["$ref"] = reqSchemaRef }
							}
						}
					};
				}

				paths[routePath] = new Dictionary<string, object>
				{
					["post"] = postMethod
				};
			}

			return paths;
		}

		private static Dictionary<string, object> GenerateJsonSchemas(XmlSchemaSet schemas)
		{
			var jsonSchemas = new Dictionary<string, object>();

			foreach (XmlSchema schema in schemas.Schemas())
			{
				// Generate from global types
				foreach (XmlSchemaType type in schema.SchemaTypes.Values)
				{
					if (type is XmlSchemaComplexType complexType)
					{
						var name = SanitizeName(complexType.Name);
						if (!string.IsNullOrEmpty(name))
						{
							jsonSchemas[name] = MapComplexTypeToSchema(complexType);
						}
					}
					else if (type is XmlSchemaSimpleType simpleType && simpleType.Content is XmlSchemaSimpleTypeRestriction restriction)
					{
						var name = SanitizeName(simpleType.Name);
						if (!string.IsNullOrEmpty(name))
						{
							jsonSchemas[name] = MapSimpleTypeToSchema(restriction);
						}
					}
				}

				// Generate from global elements (often request/response elements)
				foreach (XmlSchemaElement el in schema.Elements.Values)
				{
					var name = SanitizeName(el.Name);
					if (!string.IsNullOrEmpty(name) && !jsonSchemas.ContainsKey(name))
					{
						if (el.SchemaType is XmlSchemaComplexType complexType)
						{
							jsonSchemas[name] = MapComplexTypeToSchema(complexType);
						}
						else
						{
							var baseType = MapXmlTypeToJson(el.SchemaTypeName.Name);
							jsonSchemas[name] = new Dictionary<string, object>
							{
								["type"] = baseType
							};
						}
					}
				}
			}

			return jsonSchemas;
		}

		private static Dictionary<string, object> MapComplexTypeToSchema(XmlSchemaComplexType complexType)
		{
			var properties = new Dictionary<string, object>();
			var required = new List<string>();

			CollectProperties(complexType.Particle, properties, required);

			var schema = new Dictionary<string, object>
			{
				["type"] = "object",
				["properties"] = properties
			};

			if (required.Count > 0)
			{
				schema["required"] = required;
			}

			return schema;
		}

		private static Dictionary<string, object> MapSimpleTypeToSchema(XmlSchemaSimpleTypeRestriction restriction)
		{
			var enumValues = new List<string>();
			foreach (var facet in restriction.Facets)
			{
				if (facet is XmlSchemaEnumerationFacet enumFacet && enumFacet.Value != null)
				{
					enumValues.Add(enumFacet.Value);
				}
			}

			var type = MapXmlTypeToJson(restriction.BaseTypeName.Name);

			var schema = new Dictionary<string, object>
			{
				["type"] = type
			};

			if (enumValues.Count > 0)
			{
				schema["enum"] = enumValues;
			}

			return schema;
		}

		private static void CollectProperties(XmlSchemaParticle? particle, Dictionary<string, object> properties, List<string> required)
		{
			if (particle == null) return;

			if (particle is XmlSchemaSequence sequence)
			{
				foreach (var item in sequence.Items)
				{
					CollectParticle(item, properties, required);
				}
			}
			else if (particle is XmlSchemaChoice choice)
			{
				foreach (var item in choice.Items)
				{
					CollectParticle(item, properties, required);
				}
			}
			else if (particle is XmlSchemaAll all)
			{
				foreach (var item in all.Items)
				{
					CollectParticle(item, properties, required);
				}
			}
		}

		private static void CollectParticle(XmlSchemaObject item, Dictionary<string, object> properties, List<string> required)
		{
			if (item is XmlSchemaElement element)
			{
				var name = element.Name ?? element.RefName.Name;
				if (string.IsNullOrEmpty(name)) return;

				var isArray = element.MaxOccurs > 1 || element.MaxOccursString == "unbounded";
				var isRequired = element.MinOccurs > 0;

				if (isRequired)
				{
					required.Add(name);
				}

				var typeName = element.SchemaTypeName.Name;
				var propSchema = new Dictionary<string, object>();

				if (isArray)
				{
					propSchema["type"] = "array";
					var itemsSchema = new Dictionary<string, object>();

					if (!string.IsNullOrEmpty(typeName))
					{
						var jsonType = MapXmlTypeToJson(typeName);
						if (jsonType == "object")
						{
							itemsSchema["$ref"] = $"#/components/schemas/{SanitizeName(typeName)}";
						}
						else
						{
							itemsSchema["type"] = jsonType;
							AddFormat(itemsSchema, typeName);
						}
					}
					else
					{
						itemsSchema["type"] = "object";
					}

					propSchema["items"] = itemsSchema;
				}
				else
				{
					if (!string.IsNullOrEmpty(typeName))
					{
						var jsonType = MapXmlTypeToJson(typeName);
						if (jsonType == "object")
						{
							propSchema["$ref"] = $"#/components/schemas/{SanitizeName(typeName)}";
						}
						else
						{
							propSchema["type"] = jsonType;
							AddFormat(propSchema, typeName);
						}
					}
					else
					{
						propSchema["type"] = "object";
					}
				}

				properties[name] = propSchema;
			}
			else if (item is XmlSchemaGroupRef groupRef)
			{
				CollectProperties(groupRef.Particle, properties, required);
			}
			else if (item is XmlSchemaChoice choice)
			{
				CollectProperties(choice, properties, required);
			}
			else if (item is XmlSchemaSequence sequence)
			{
				CollectProperties(sequence, properties, required);
			}
		}

		private static string MapXmlTypeToJson(string typeName)
		{
			if (string.IsNullOrEmpty(typeName)) return "object";

			switch (typeName.ToLowerInvariant())
			{
				case "string":
				case "anyuri":
				case "datetime":
				case "date":
					return "string";
				case "boolean":
					return "boolean";
				case "int":
				case "integer":
				case "long":
				case "short":
					return "integer";
				case "decimal":
				case "float":
				case "double":
					return "number";
				default:
					return "object";
			}
		}

		private static void AddFormat(Dictionary<string, object> schema, string typeName)
		{
			switch (typeName.ToLowerInvariant())
			{
				case "datetime":
				case "date":
					schema["format"] = "date-time";
					break;
				case "long":
					schema["format"] = "int64";
					break;
				case "int":
				case "integer":
					schema["format"] = "int32";
					break;
			}
		}

		private static string SanitizeName(string? name)
		{
			if (string.IsNullOrEmpty(name)) return string.Empty;
			return name.Replace(":", "_");
		}
	}
}
