using System.Text;
using System.Xml.Schema;

namespace SmartWsdlKit
{
	/// <summary>
	/// Configuration options for code generation.
	/// </summary>
	public class CodeGeneratorOptions
	{
		/// <summary>
		/// Gets or sets the target namespace of the generated classes. Default is "SmartWsdlKit.Generated".
		/// </summary>
		public string Namespace { get; set; } = "SmartWsdlKit.Generated";

		/// <summary>
		/// Gets or sets a value indicating whether to generate C# 9.0 Records instead of standard POCO classes. Default is false.
		/// </summary>
		public bool GenerateRecords { get; set; } = false;

		/// <summary>
		/// Gets or sets a value indicating whether to make reference types nullable (C# Nullable Reference Types). Default is true.
		/// </summary>
		public bool EnableNullableReferenceTypes { get; set; } = true;
	}

	/// <summary>
	/// Generates C# DTOs, interfaces, and clients from a WsdlDocument.
	/// </summary>
	public static class WsdlCodeGenerator
	{
		/// <summary>
		/// Generates C# source code from WSDL metadata using default options.
		/// </summary>
		public static string Generate(WsdlDocument wsdl)
		{
			return Generate(wsdl, new CodeGeneratorOptions());
		}

		/// <summary>
		/// Generates C# source code from WSDL metadata with specified options.
		/// </summary>
		public static string Generate(WsdlDocument wsdl, CodeGeneratorOptions options)
		{
			if (wsdl == null)
				throw new ArgumentNullException(nameof(wsdl));
			if (options == null)
				throw new ArgumentNullException(nameof(options));

			var sb = new StringBuilder();
			sb.AppendLine("//------------------------------------------------------------------------------");
			sb.AppendLine("// <auto-generated>");
			sb.AppendLine("//     This code was generated by SmartWsdlKit.");
			sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
			sb.AppendLine("//     the code is regenerated.");
			sb.AppendLine("// </auto-generated>");
			sb.AppendLine("//------------------------------------------------------------------------------");
			sb.AppendLine();
			sb.AppendLine(@"using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Xml.Serialization;
using SmartWsdlKit;");
			sb.AppendLine();
			sb.AppendLine($"namespace {options.Namespace}");
			sb.AppendLine("{");

			var generatedTypes = new HashSet<string>();

			// 1. Generate Enums from SimpleTypes
			GenerateEnums(wsdl.Schemas, sb, generatedTypes);

			// 2. Generate DTOs from ComplexTypes and Elements
			GenerateDtos(wsdl.Schemas, sb, options, generatedTypes);

			// 3. Generate Service Client and Interfaces
			GenerateClientAndInterface(wsdl, sb, options);

			sb.AppendLine("}");
			return sb.ToString();
		}

		private static void GenerateEnums(XmlSchemaSet schemas, StringBuilder sb, HashSet<string> generatedTypes)
		{
			foreach (XmlSchema schema in schemas.Schemas())
			{
				foreach (XmlSchemaType type in schema.SchemaTypes.Values)
				{
					if (type is XmlSchemaSimpleType simpleType && simpleType.Content is XmlSchemaSimpleTypeRestriction restriction)
					{
						var typeName = SanitizeIdentifier(simpleType.Name);
						if (string.IsNullOrEmpty(typeName) || !generatedTypes.Add(typeName)) continue;

						sb.AppendLine($"    /// <summary>");
						sb.AppendLine($"    /// Generated enum for {simpleType.Name}");
						sb.AppendLine($"    /// </summary>");
						sb.AppendLine($"    public enum {typeName}");
						sb.AppendLine("    {");

						int valIndex = 0;
						foreach (var facet in restriction.Facets)
						{
							if (facet is XmlSchemaEnumerationFacet enumFacet)
							{
								var rawValue = enumFacet.Value;
								var safeName = SanitizeIdentifier(rawValue);
								if (string.IsNullOrEmpty(safeName)) safeName = "Value_" + valIndex;

								sb.AppendLine($"        [XmlEnum(\"{rawValue}\")]");
								sb.AppendLine($"        {safeName},");
								valIndex++;
							}
						}

						sb.AppendLine("    }");
						sb.AppendLine();
					}
				}
			}
		}

		private static void GenerateDtos(XmlSchemaSet schemas, StringBuilder sb, CodeGeneratorOptions options, HashSet<string> generatedTypes)
		{
			foreach (XmlSchema schema in schemas.Schemas())
			{
				// Generate from Global Types
				foreach (XmlSchemaType type in schema.SchemaTypes.Values)
				{
					if (type is XmlSchemaComplexType complexType)
					{
						var typeName = SanitizeIdentifier(complexType.Name);
						if (string.IsNullOrEmpty(typeName) || !generatedTypes.Add(typeName)) continue;

						GenerateComplexTypeClass(typeName, complexType, sb, options);
					}
				}

				// Generate from Global Elements that define anonymous complex types inline
				foreach (XmlSchemaElement el in schema.Elements.Values)
				{
					var complexType = el.SchemaType as XmlSchemaComplexType ?? el.ElementSchemaType as XmlSchemaComplexType;
					if (complexType != null && string.IsNullOrEmpty(complexType.Name))
					{
						var typeName = SanitizeIdentifier(el.Name);
						if (string.IsNullOrEmpty(typeName) || !generatedTypes.Add(typeName)) continue;

						GenerateComplexTypeClass(typeName, complexType, sb, options);
					}
				}
			}
		}

		private static void GenerateComplexTypeClass(string typeName, XmlSchemaComplexType complexType, StringBuilder sb, CodeGeneratorOptions options)
		{
			sb.AppendLine("    [System.SerializableAttribute]");
			sb.AppendLine($"    public {(options.GenerateRecords ? "record" : "class")} {typeName}");
			sb.AppendLine("    {");

			var properties = new List<GeneratedProperty>();
			CollectProperties(complexType.Particle, properties, options);

			foreach (var prop in properties)
			{
				sb.AppendLine($"        [XmlElementAttribute(ElementName = \"{prop.XmlName}\")]");
				sb.AppendLine($"        public {prop.CSharpType} {prop.Name} {{ get; set; }} = {prop.Initializer};");
				sb.AppendLine();
			}

			sb.AppendLine("    }");
			sb.AppendLine();
		}

		private static void CollectProperties(XmlSchemaParticle? particle, List<GeneratedProperty> properties, CodeGeneratorOptions options)
		{
			if (particle == null) return;

			if (particle is XmlSchemaSequence sequence)
			{
				foreach (var item in sequence.Items)
				{
					CollectParticle(item, properties, options);
				}
			}
			else if (particle is XmlSchemaChoice choice)
			{
				foreach (var item in choice.Items)
				{
					CollectParticle(item, properties, options);
				}
			}
			else if (particle is XmlSchemaAll all)
			{
				foreach (var item in all.Items)
				{
					CollectParticle(item, properties, options);
				}
			}
		}

		private static void CollectParticle(XmlSchemaObject item, List<GeneratedProperty> properties, CodeGeneratorOptions options)
		{
			if (item is XmlSchemaElement element)
			{
				var xmlName = element.Name ?? element.RefName.Name;
				var safeName = SanitizeIdentifier(xmlName);
				if (string.IsNullOrEmpty(safeName)) return;

				var isArray = element.MaxOccurs > 1 || element.MaxOccursString == "unbounded";
				var isNullable = element.MinOccurs == 0 || element.IsNillable;

				var xmlTypeName = element.SchemaTypeName.Name;
				if (string.IsNullOrEmpty(xmlTypeName) && element.SchemaType != null)
				{
					xmlTypeName = element.SchemaType.Name;
				}

				var baseType = MapXmlTypeToCSharp(xmlTypeName, element.SchemaTypeName.Namespace);

				string csharpType;
				string initializer;

				if (isArray)
				{
					csharpType = $"List<{baseType}>";
					initializer = $"new List<{baseType}>()";
				}
				else
				{
					if (isNullable && IsValueType(baseType))
					{
						csharpType = baseType + "?";
						initializer = "null";
					}
					else if (options.EnableNullableReferenceTypes && !IsValueType(baseType))
					{
						csharpType = baseType + "?";
						initializer = "null";
					}
					else
					{
						csharpType = baseType;
						initializer = GetDefaultValue(baseType);
					}
				}

				properties.Add(new GeneratedProperty
				{
					Name = safeName,
					XmlName = xmlName,
					CSharpType = csharpType,
					Initializer = initializer
				});
			}
			else if (item is XmlSchemaGroupRef groupRef)
			{
				// Unroll nested groups
				CollectProperties(groupRef.Particle, properties, options);
			}
			else if (item is XmlSchemaChoice choice)
			{
				CollectProperties(choice, properties, options);
			}
			else if (item is XmlSchemaSequence sequence)
			{
				CollectProperties(sequence, properties, options);
			}
		}

		private static void GenerateClientAndInterface(WsdlDocument wsdl, StringBuilder sb, CodeGeneratorOptions options)
		{
			foreach (var wsdlInterface in wsdl.Interfaces)
			{
				var interfaceName = "I" + SanitizeIdentifier(wsdlInterface.Name);
				var clientName = SanitizeIdentifier(wsdlInterface.Name) + "Client";

				// Generate Interface
				sb.AppendLine($"    /// <summary>");
				sb.AppendLine($"    /// Service contract interface for {wsdlInterface.Name}");
				sb.AppendLine($"    /// </summary>");
				sb.AppendLine($"    public interface {interfaceName} : IDisposable");
				sb.AppendLine("    {");

				foreach (var op in wsdlInterface.Operations)
				{
					var reqType = SanitizeIdentifier(op.InputElementName ?? op.Name + "Request");
					var respType = SanitizeIdentifier(op.OutputElementName ?? op.Name + "Response");

					sb.AppendLine($"        Task<{respType}> {SanitizeIdentifier(op.Name)}Async({reqType} request, CancellationToken cancellationToken = default);");
				}

				sb.AppendLine("    }");
				sb.AppendLine();

				// Generate Client Class
				sb.AppendLine($"    /// <summary>");
				sb.AppendLine($"    /// Strongly-typed client wrapper implementing {interfaceName} using SoapClient.");
				sb.AppendLine($"    /// </summary>");
				sb.AppendLine($"    public class {clientName} : {interfaceName}");
				sb.AppendLine("    {");
				sb.AppendLine("        private readonly SoapClient _client;");
				sb.AppendLine();
				sb.AppendLine($"        public {clientName}(SoapClient client)");
				sb.AppendLine("        {");
				sb.AppendLine("            _client = client ?? throw new ArgumentNullException(nameof(client));");
				sb.AppendLine("        }");
				sb.AppendLine();
				sb.AppendLine($"        public {clientName}(SoapClientOptions options)");
				sb.AppendLine("        {");
				sb.AppendLine("            _client = new SoapClient(options);");
				sb.AppendLine("        }");
				sb.AppendLine();

				foreach (var op in wsdlInterface.Operations)
				{
					var opName = SanitizeIdentifier(op.Name);
					var reqType = SanitizeIdentifier(op.InputElementName ?? op.Name + "Request");
					var respType = SanitizeIdentifier(op.OutputElementName ?? op.Name + "Response");

					sb.AppendLine($"        public async Task<{respType}> {opName}Async({reqType} request, CancellationToken cancellationToken = default)");
					sb.AppendLine("        {");
					sb.AppendLine($"            var builder = _client.Operation(\"{op.Name}\");");

					// Reflect properties dynamically of request DTO to fill parameters
					sb.AppendLine("            if (request != null)");
					sb.AppendLine("            {");
					sb.AppendLine("                foreach (var prop in request.GetType().GetProperties())");
					sb.AppendLine("                {");
					sb.AppendLine("                    var val = prop.GetValue(request);");
					sb.AppendLine("                    builder.With(prop.Name, val);");
					sb.AppendLine("                }");
					sb.AppendLine("            }");
					sb.AppendLine();
					sb.AppendLine("            var response = await builder.ExecuteAsync(cancellationToken).ConfigureAwait(false);");
					sb.AppendLine($"            return response.As<{respType}>();");
					sb.AppendLine("        }");
					sb.AppendLine();
				}

				sb.AppendLine("        public void Dispose()");
				sb.AppendLine("        {");
				sb.AppendLine("            _client.Dispose();");
				sb.AppendLine("        }");

				sb.AppendLine("    }");
				sb.AppendLine();
			}
		}

		private static string MapXmlTypeToCSharp(string xmlTypeName, string ns)
		{
			if (string.IsNullOrEmpty(xmlTypeName)) return "object";

			switch (xmlTypeName.ToLowerInvariant())
			{
				case "string":
				case "anyuri":
					return "string";
				case "boolean":
					return "bool";
				case "int":
				case "integer":
				case "positiveinteger":
				case "negativeinteger":
				case "nonnegativeinteger":
				case "nonpositiveinteger":
					return "int";
				case "long":
					return "long";
				case "short":
					return "short";
				case "decimal":
					return "decimal";
				case "float":
					return "float";
				case "double":
					return "double";
				case "datetime":
				case "date":
					return "DateTime";
				case "base64binary":
					return "byte[]";
				default:
					// Return type name matching complex type schemas
					return SanitizeIdentifier(xmlTypeName);
			}
		}

		private static bool IsValueType(string type)
		{
			switch (type)
			{
				case "bool":
				case "int":
				case "long":
				case "short":
				case "decimal":
				case "float":
				case "double":
				case "DateTime":
					return true;
				default:
					return false;
			}
		}

		private static string GetDefaultValue(string type)
		{
			switch (type)
			{
				case "bool":
					return "false";
				case "int":
				case "long":
				case "short":
					return "0";
				case "decimal":
					return "0m";
				case "float":
					return "0f";
				case "double":
					return "0d";
				case "DateTime":
					return "default(DateTime)";
				case "string":
					return "string.Empty";
				default:
					return "null!";
			}
		}

		private static string SanitizeIdentifier(string? name)
		{
			if (string.IsNullOrEmpty(name)) return string.Empty;

			var sb = new StringBuilder();
			bool makeUpper = true;

			foreach (char c in name)
			{
				if (char.IsLetterOrDigit(c))
				{
					sb.Append(makeUpper ? char.ToUpperInvariant(c) : c);
					makeUpper = false;
				}
				else
				{
					makeUpper = true;
				}
			}

			var result = sb.ToString();

			// Cannot start with number
			if (result.Length > 0 && char.IsDigit(result[0]))
			{
				result = "Num" + result;
			}

			return result;
		}

		private class GeneratedProperty
		{
			public string Name { get; set; } = string.Empty;
			public string XmlName { get; set; } = string.Empty;
			public string CSharpType { get; set; } = string.Empty;
			public string Initializer { get; set; } = string.Empty;
		}
	}
}
